# Generated by Django 4.2 on 2024-08-16 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_categorie_gmail"),
    ]

    operations = [
        migrations.AddField(
            model_name="gmail_message",
            name="categorie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.categorie_gmail",
            ),
        ),
        migrations.AlterField(
            model_name="categorie_gmail",
            name="Contenu",
            field=models.TextField(max_length=50, unique=True),
        ),
    ]
