# Generated by Django 4.2 on 2024-08-16 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_gmail_message_categorie_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorie_gmail",
            name="Contenu",
            field=models.TextField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="envoyer_message",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="envoyer_message_set",
                to="chat.gmail_message",
            ),
        ),
    ]
